### ISSUE TITLE
Issue with JSON on Vercel

### ISSUE THREAD

**Issue by abdinal1** [langgenius/webapp-conversation#12]
Hello,

When pushing the repo to vercel I can type a chat message, seldom it does deliever an answer and mostly an JSON error appears:

"SyntaxError: Unterminated string in JSON at position 129"

This error always pops up when I want to type something, why is that so? Please help me.

**Comment by abdinal1** [comment]
Do you have any ideas @goocarlos @iamjoel @jingjingxinshang @crazywoola ?

**Comment by yalefox** [comment]
We're getting the same errors - it happens when you modify config.ts

**Comment by abdinal1** [comment]
@yalefox And what is the solution ?

**Comment by iamjoel** [comment]
This issue is a duplicate of https://github.com/langgenius/webapp-conversation/issues/13
