### ISSUE TITLE
SyntaxError: Unterminated string in JSON at position 135

### ISSUE THREAD

**Issue by shundao-haihe** [langgenius/webapp-conversation#13]
SyntaxError: Unterminated string in JSON at position 135；对话的时候一直出现这个错误，然后对话终止。

**Comment by abdinal1** [comment]
@shundao-haihe Did you find a solution?

**Comment by isunkit** [comment]
我也是这样，是部署到vercel的原因吗？还有这种 SyntaxError: Bad Unicode escape in JSON at position 134

**Comment by Gitmaxd** [comment]
Facing the same issue with deployment on Vercel.  Any temp fix?

**Comment by ZaiQi-zq** [comment]
为什么我导入vercel上部署要很久很久
![image](https://github.com/langgenius/webapp-conversation/assets/129143636/8e31c49e-b241-4622-a42a-e26459f017a8)

**Comment by hcj5206** [comment]
me too

**Comment by kemeny** [comment]
same issue

**Comment by eduwass** [comment]
+1

**Comment by Zhouchuanwen** [comment]
> same issue, depoly with docker, not vercel environment !

Hey guys, I solved my case with the following configurations in `Nginx SSE` support:

keepalive_timeout  600;
client_body_timeout 600;
send_timeout 86400;
add_header Cache-Control 'no-cache';
add_header Connection 'keep-alive';

proxy_buffering off;
proxy_read_timeout 86400s;

**Comment by abdinal1** [comment]
> > same issue, depoly with docker, not vercel environment !
> 
> Hey guys, I solved my case with the following configurations in `Nginx SSE` support:
> 
> keepalive_timeout 600; client_body_timeout 600; send_timeout 86400; add_header Cache-Control 'no-cache'; add_header Connection 'keep-alive';
> 
> proxy_buffering off; proxy_read_timeout 86400s;

Where to add that in a file in github or is it possible on vercel?

**Comment by Zhouchuanwen** [comment]
> > > same issue, depoly with docker, not vercel environment !
> > 
> > 
> > Hey guys, I solved my case with the following configurations in `Nginx SSE` support:
> > keepalive_timeout 600; client_body_timeout 600; send_timeout 86400; add_header Cache-Control 'no-cache'; add_header Connection 'keep-alive';
> > proxy_buffering off; proxy_read_timeout 86400s;
> 
> Where to add that in a file in github or is it possible on vercel?

As the README said, vercel hobby has it's limitation, so you need to upgrade to pro or deploy the project on your own server and config it in your nginx.conf file.

**Comment by eduwass** [comment]
> As the README said, vercel hobby has it's limitation, so you need to upgrade to pro or deploy the project on your own server and config it in your nginx.conf file.

I'm on Vercel Pro and it's doing this 😑

**Comment by Numi2** [comment]
Having the same issue on Vercel Pro

**Comment by takatost** [comment]
I reproduced the issue. We will fix it as soon as possible.

**Comment by Numi2** [comment]
I deployed with netlify, this time it happens when the responses takess too much time. But when I refresh the page, the answer is there.

**Comment by iamjoel** [comment]
Fixd: https://github.com/langgenius/webapp-conversation/pull/22 and https://github.com/langgenius/webapp-conversation/pull/23
