### ISSUE TITLE
It is possible to use this webapp with an external application ?

### ISSUE THREAD

**Issue by techguruagi** [langgenius/webapp-conversation#20]
It is possible to use this webapp with an external application ?. If so, any pointer is appreciated. 

All i need is to send the incoming message to the external app as a webhook and receive messages from the external app via an api call ?

Thanks in advance

**Comment by iamjoel** [comment]
Yes, you can use embed in [cloud version](https://cloud.dify.ai)
<img width="1171" alt="image" src="https://github.com/langgenius/webapp-conversation/assets/2120155/646aeb1d-f4ad-4888-aece-c92a1f54c24f">

**Comment by techguruagi** [comment]
Thanks @iamjoel for your prompt response. My question is about pragmatically integrate and send/receive the messages with an external app.
