### ISSUE TITLE
启动后打开http://localhost:3000报错

### ISSUE THREAD

**Issue by yinhaixiang** [langgenius/webapp-conversation#25]
系统: macos(12.2.1)
nodejs: v18.17.1
浏览器: chrome最新
npm install后npm run dev报错:
<img width="963" alt="image" src="https://github.com/langgenius/webapp-conversation/assets/10047441/5d2f0d30-bf9a-4d2e-967d-7bed8b9519be">

**Comment by iamjoel** [comment]
Unable to reproduce, try again after pulling the latest code.
