### ISSUE TITLE
请问.env.local的这些参数是分别那个创建的应用的appid和apikey还有api地址吗

### ISSUE THREAD

**Issue by zjrwtxdaydayup** [langgenius/webapp-conversation#31]
![image](https://github.com/langgenius/webapp-conversation/assets/139489333/68e04046-1f52-4540-881a-8487eac3c9e7)

**Comment by dxtbrave** [comment]
APP_KEY 对应 API密钥
NEXT_PUBLIC_API_URL 对应 API文档中的地址
