### ISSUE TITLE
500 App is unavailable

### ISSUE THREAD

**Issue by TigrisRiva** [langgenius/webapp-conversation#37]
I've set the correct .env.local file correctly and after I run **npm run dev** 
I got a 500 App is unavailable error on the localhost:3000.
I'm not sure where I went wrong with the configuration.
Can I see any logs?

**Comment by levie-vans** [comment]
I have the same problem.

**Comment by sean233** [comment]
same problem!

**Comment by levie-vans** [comment]
I've found that modifying the corresponding sections in two program files can resolve this issue. It appears to be a bug in the program.
![image](https://github.com/langgenius/webapp-conversation/assets/66657337/1ce412fe-3c4c-46df-a090-45d5e41f31ec)
![image](https://github.com/langgenius/webapp-conversation/assets/66657337/c6e06650-a6df-424a-8899-6bb8163fd55f)
![image](https://github.com/langgenius/webapp-conversation/assets/66657337/3903fea0-142c-4e35-b386-7bc963e00580)

**Comment by TigrisRiva** [comment]
不用英文说了
问题找到了。env.local里，不要引号，不要引号，不要引号
重要的问题说三遍
