### ISSUE TITLE
throw this error when build after add Environment Variables in vercel

### ISSUE THREAD

**Issue by ImpChiang** [langgenius/webapp-conversation#50]
![微信截图_20240313174527](https://github.com/langgenius/webapp-conversation/assets/31588565/9d13e1c8-7535-4d37-818b-423c27303507)

**Comment by crazywoola** [comment]
<img width="423" alt="image" src="https://github.com/langgenius/webapp-conversation/assets/100913391/471ea9b0-3233-4f02-98f0-274a5b09e6ee">

**Comment by ImpChiang** [comment]
I tryied several times with doc，but，its build fail just after add  APP_ID，API_KEY and API_URL，so how to deploy with new APP_ID，API_KEY and API_URL ？

**Comment by crazywoola** [comment]
It should be these 3
```
# APP ID
NEXT_PUBLIC_APP_ID=
# APP API key
NEXT_PUBLIC_APP_KEY=
# APP URL
NEXT_PUBLIC_API_URL=
```

**Comment by ImpChiang** [comment]
![1710400835329](https://github.com/langgenius/webapp-conversation/assets/31588565/81540928-06de-4796-8d65-07d41eefb43d)
![1710400859427](https://github.com/langgenius/webapp-conversation/assets/31588565/d137ad71-a003-4c24-a5ff-0becdc2590f7)
yes，add env in root，still build fail，first time deploy nextjs，not familiar with this

**Comment by ImpChiang** [comment]
// next.config.js
`module.exports = {
 staticPageGenerationTimeout: 1000,
}`
use this to increase timeout to collect page data and it works,. thx
