### ISSUE TITLE
代码是2个月前的 需要更新到最新代码

### ISSUE THREAD

**Issue by jiahuamld** [langgenius/webapp-conversation#52]
代码是2个月前的 需要更新到最新代码与在线界面保持一致

**Comment by QJBChou** [comment]
这个代码仓还会更新吗

**Comment by tatiane-leal** [comment]
Would be great to have the `suggestions` feature implemented.

**Comment by dxtbrave** [comment]
现在还没有更新至最新版

**Comment by iamjoel** [comment]
We only sync some important and necessary features here.
