### ISSUE TITLE
"500 App is unavailable" when fetching empty conversations

### ISSUE THREAD

**Issue by stepacool** [langgenius/webapp-conversation#67]
I pulled the repository to my local machine and set the required environment variables. After I started the project with 
`npm run dev`
It starts and all the requests are 200 OK, but the whole screen is a big 500 App is unavailable. 
I reversed engineered the issue and it seems this is happening due to an empty body of /conversations/ API request. Attaching screenshots with error, error logging and potential source of problem.
![Screenshot from 2024-04-26 23-46-55](https://github.com/langgenius/webapp-conversation/assets/18003338/dad18809-3a08-44b8-bbca-b5c35988ea65)
![Screenshot from 2024-04-26 23-49-48](https://github.com/langgenius/webapp-conversation/assets/18003338/ddda240c-5bc1-4c0f-b7c0-4f77cfe638b5)
![Screenshot from 2024-04-26 23-50-09](https://github.com/langgenius/webapp-conversation/assets/18003338/e2df691d-e3e0-4389-9e71-b529dcc7a559)
![Screenshot from 2024-04-26 23-51-24](https://github.com/langgenius/webapp-conversation/assets/18003338/a155c85d-281a-4d45-ad04-c10eafae369e)
![Screenshot from 2024-04-26 23-50-50](https://github.com/langgenius/webapp-conversation/assets/18003338/bc6b4713-6e96-439f-9f17-08eb14dee83c)
Screenshots show that the error is raised here:
`        const isNotNewConversation = conversations.some(item => item.id === _conversationId)
`
But gets muted and instead setAppUnavailable() is called.
The error reads "TypeError: Cannot read properties of undefined (reading 'some')
    at eval (index.tsx:228:52)" meaning the supposed list conversations is undefined at the moment.

**Comment by flyfish01** [comment]
i have same problem. TypeError: conversations is undefined.


TypeError: conversations is undefined
    Main index.tsx:236
    Main index.tsx:277
    commitHookEffectListMount react-dom.development.js:21102
    commitHookPassiveMountEffects react-dom.development.js:23154
    commitPassiveMountOnFiber react-dom.development.js:23259

**Comment by kronus-ho** [comment]
我也有同样的问题，我的设置如下：
![1](https://github.com/langgenius/webapp-conversation/assets/160586486/4140758f-f537-41ef-b4ef-6db312c07d11)
![2](https://github.com/langgenius/webapp-conversation/assets/160586486/8ebc2ab2-b34e-4d24-a2df-b80f7b08b02b)


是我设置有问题吗？
![3](https://github.com/langgenius/webapp-conversation/assets/160586486/a51e6820-4c88-4b83-8c79-9f7f7b369821)

**Comment by cuixin992173697** [comment]
I have the same problem, the page show "500 | app is unavailable" ,

![企业微信截图_c5f62f33-0860-4974-bc5d-848067123d0c](https://github.com/user-attachments/assets/ec251d34-073d-4a9f-a671-569eb677ab1b)

**Comment by marsDes** [comment]
confirm you app type is Conversation Application
and has created env.local file  like this
```
NEXT_PUBLIC_APP_ID='<Your app Id>' 
NEXT_PUBLIC_APP_KEY='<Web API Key From Dify>' 
NEXT_PUBLIC_API_URL='https://api.dify.ai/v1'
```

**Comment by hponiang** [comment]
检查本地是否开了代理，把代理完全关闭去掉。

**Comment by iamjoel** [comment]
Maybe caused by not set NEXT_PUBLIC_API_URL or set the wrong NEXT_PUBLIC_API_URL value? @stepacool

**Comment by hqz010** [comment]
经过调试测试跟踪，发现错误是以下引起的，发现如果配置的后台ai agent的prompt中配置了变量就会出错这个问题，如果换一个没有配变量的ai agent或是助手时就可以正常的启动运行

**Comment by iamjoel** [comment]
> 经过调试测试跟踪，发现错误是以下引起的，发现如果配置的后台ai agent的prompt中配置了变量就会出错这个问题，如果换一个没有配变量的ai agent或是助手时就可以正常的启动运行

Still can't reproduce after I add the variable in prompt in an agent chat app. @hqz010

**Comment by hqz010** [comment]
昨天的那个版本代码，因该是一些代码没有合并进来，见如下，线上可以配置5种变量类型
<img width="148" alt="1725415965981" src="https://github.com/user-attachments/assets/dfcc6ea6-841e-4a7b-ac99-d0e3318bd7ea">
但是prompt.ts中代码有三种
<img width="543" alt="1725415816433" src="https://github.com/user-attachments/assets/bd0918b7-af60-4ebe-aed7-dbb1c0bd8d25">
在app.ts中只定义了两种变量类型
<img width="233" alt="1725416141752" src="https://github.com/user-attachments/assets/241b70d7-d37e-412d-b15f-24b6afe004f6">
<img width="223" alt="e605960b52a2121b0eef4b4890e223a" src="https://github.com/user-attachments/assets/67496fab-0d01-4929-9d38-72d0dd6f5de1">
因该是代码没有合并全
@iamjoel

**Comment by turndown** [comment]
> 昨天的那个版本代码，因该是一些代码没有合并进来，见如下，线上可以配置5种变量类型 <img alt="1725415965981" width="148" src="https://private-user-images.githubusercontent.com/3402807/364199857-dfcc6ea6-841e-4a7b-ac99-d0e3318bd7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDE5OTg1Ny1kZmNjNmVhNi04NDFlLTRhN2ItYWM5OS1kMGUzMzE4YmQ3ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYxNmI3NWQ3NzUyZTQyOWQxYmExZjhmMzczNmFhNTY3YzhmN2I0ZTYwZjdiMGQ4YmFkMmJlMjI3M2RjMDA2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mj_i4u_O4awpK8zS1dqleMGYrFSRuw1OPjyPHnwy2BQ"> 但是prompt.ts中代码有三种 <img alt="1725415816433" width="543" src="https://private-user-images.githubusercontent.com/3402807/364200070-bd0918b7-af60-4ebe-aed7-dbb1c0bd8d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDA3MC1iZDA5MThiNy1hZjYwLTRlYmUtYWVkNy1kYmIxYzBiZDhkMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IwNzQ3NjAzMzRkZGI4YzJiYWZiN2JmZGQ3NDFmMWUzYTU0MTMwOTNhZDcwNGY0NDc2NmI5NWVkYjNiYTcxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hOTgP2JEsjmq-aAWSKL--fJ51rmC-X-wPCPDITdnSaY"> 在app.ts中只定义了两种变量类型 <img alt="1725416141752" width="233" src="https://private-user-images.githubusercontent.com/3402807/364200334-241b70d7-d37e-412d-b15f-24b6afe004f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDMzNC0yNDFiNzBkNy1kMzdlLTQxMmQtYjE1Zi0yNGI2YWZlMDA0ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFiMGQ2MzJhNGExZjRkZDNkMmQwM2YyNzhkMmY4NjY2NTc0NGMzMjBkNTkzNzE0NzU3NjMyYWU0OTRmOTRhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v6G_d0kICiro5Uyq-5-IfqSzl6PujwBWFVlA6ZhYOEA"> <img alt="e605960b52a2121b0eef4b4890e223a" width="223" src="https://private-user-images.githubusercontent.com/3402807/364200476-67496fab-0d01-4929-9d38-72d0dd6f5de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDQ3Ni02NzQ5NmZhYi0wZDAxLTQ5MjktOWQzOC03MmQwZGQ2ZjVkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ2MjZjMmNlZTI1ZjBjNGU1NGQ3NWFkNmYwYmVjODA2YjAzZjY2OTdlZjkxM2YyM2RhODUzODdhOWMyM2Y5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.78zj_PKe81ZZp120uKZC54EkaJs6KvFAbNwM3cLjCQI"> 因该是代码没有合并全 @iamjoel

我今天拉了代码，运行还是报这个错误。请问下env的三个参数，NEXT_PUBLIC_APP_ID填的是dify里对应的什么参数？

**Comment by iamjoel** [comment]
> > 昨天的那个版本代码，因该是一些代码没有合并进来，见如下，线上可以配置5种变量类型 <img alt="1725415965981" width="148" src="https://private-user-images.githubusercontent.com/3402807/364199857-dfcc6ea6-841e-4a7b-ac99-d0e3318bd7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDE5OTg1Ny1kZmNjNmVhNi04NDFlLTRhN2ItYWM5OS1kMGUzMzE4YmQ3ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYxNmI3NWQ3NzUyZTQyOWQxYmExZjhmMzczNmFhNTY3YzhmN2I0ZTYwZjdiMGQ4YmFkMmJlMjI3M2RjMDA2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mj_i4u_O4awpK8zS1dqleMGYrFSRuw1OPjyPHnwy2BQ"> 但是prompt.ts中代码有三种 <img alt="1725415816433" width="543" src="https://private-user-images.githubusercontent.com/3402807/364200070-bd0918b7-af60-4ebe-aed7-dbb1c0bd8d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDA3MC1iZDA5MThiNy1hZjYwLTRlYmUtYWVkNy1kYmIxYzBiZDhkMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IwNzQ3NjAzMzRkZGI4YzJiYWZiN2JmZGQ3NDFmMWUzYTU0MTMwOTNhZDcwNGY0NDc2NmI5NWVkYjNiYTcxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hOTgP2JEsjmq-aAWSKL--fJ51rmC-X-wPCPDITdnSaY"> 在app.ts中只定义了两种变量类型 <img alt="1725416141752" width="233" src="https://private-user-images.githubusercontent.com/3402807/364200334-241b70d7-d37e-412d-b15f-24b6afe004f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDMzNC0yNDFiNzBkNy1kMzdlLTQxMmQtYjE1Zi0yNGI2YWZlMDA0ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFiMGQ2MzJhNGExZjRkZDNkMmQwM2YyNzhkMmY4NjY2NTc0NGMzMjBkNTkzNzE0NzU3NjMyYWU0OTRmOTRhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v6G_d0kICiro5Uyq-5-IfqSzl6PujwBWFVlA6ZhYOEA"> <img alt="e605960b52a2121b0eef4b4890e223a" width="223" src="https://private-user-images.githubusercontent.com/3402807/364200476-67496fab-0d01-4929-9d38-72d0dd6f5de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDQ3Ni02NzQ5NmZhYi0wZDAxLTQ5MjktOWQzOC03MmQwZGQ2ZjVkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ2MjZjMmNlZTI1ZjBjNGU1NGQ3NWFkNmYwYmVjODA2YjAzZjY2OTdlZjkxM2YyM2RhODUzODdhOWMyM2Y5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.78zj_PKe81ZZp120uKZC54EkaJs6KvFAbNwM3cLjCQI"> 因该是代码没有合并全 @iamjoel
> 
> 我今天拉了代码，运行还是报这个错误。请问下env的三个参数，NEXT_PUBLIC_APP_ID填的是dify里对应的什么参数？

You can find the app id in the url of app detail page.
<img width="611" alt="image" src="https://github.com/user-attachments/assets/67a0e54e-4df9-432b-8785-69856f219c99">

**Comment by turndown** [comment]
> > > 昨天的那个版本代码，因该是一些代码没有合并进来，见如下，线上可以配置5种变量类型 <img alt="1725415965981" width="148" src="https://private-user-images.githubusercontent.com/3402807/364199857-dfcc6ea6-841e-4a7b-ac99-d0e3318bd7ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDE5OTg1Ny1kZmNjNmVhNi04NDFlLTRhN2ItYWM5OS1kMGUzMzE4YmQ3ZWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYxNmI3NWQ3NzUyZTQyOWQxYmExZjhmMzczNmFhNTY3YzhmN2I0ZTYwZjdiMGQ4YmFkMmJlMjI3M2RjMDA2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mj_i4u_O4awpK8zS1dqleMGYrFSRuw1OPjyPHnwy2BQ"> 但是prompt.ts中代码有三种 <img alt="1725415816433" width="543" src="https://private-user-images.githubusercontent.com/3402807/364200070-bd0918b7-af60-4ebe-aed7-dbb1c0bd8d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDA3MC1iZDA5MThiNy1hZjYwLTRlYmUtYWVkNy1kYmIxYzBiZDhkMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IwNzQ3NjAzMzRkZGI4YzJiYWZiN2JmZGQ3NDFmMWUzYTU0MTMwOTNhZDcwNGY0NDc2NmI5NWVkYjNiYTcxYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hOTgP2JEsjmq-aAWSKL--fJ51rmC-X-wPCPDITdnSaY"> 在app.ts中只定义了两种变量类型 <img alt="1725416141752" width="233" src="https://private-user-images.githubusercontent.com/3402807/364200334-241b70d7-d37e-412d-b15f-24b6afe004f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDMzNC0yNDFiNzBkNy1kMzdlLTQxMmQtYjE1Zi0yNGI2YWZlMDA0ZjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGFiMGQ2MzJhNGExZjRkZDNkMmQwM2YyNzhkMmY4NjY2NTc0NGMzMjBkNTkzNzE0NzU3NjMyYWU0OTRmOTRhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.v6G_d0kICiro5Uyq-5-IfqSzl6PujwBWFVlA6ZhYOEA"> <img alt="e605960b52a2121b0eef4b4890e223a" width="223" src="https://private-user-images.githubusercontent.com/3402807/364200476-67496fab-0d01-4929-9d38-72d0dd6f5de1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTc0NDgsIm5iZiI6MTcyNjIxNzE0OCwicGF0aCI6Ii8zNDAyODA3LzM2NDIwMDQ3Ni02NzQ5NmZhYi0wZDAxLTQ5MjktOWQzOC03MmQwZGQ2ZjVkZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDg0NTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzQ2MjZjMmNlZTI1ZjBjNGU1NGQ3NWFkNmYwYmVjODA2YjAzZjY2OTdlZjkxM2YyM2RhODUzODdhOWMyM2Y5YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.78zj_PKe81ZZp120uKZC54EkaJs6KvFAbNwM3cLjCQI"> 因该是代码没有合并全 @iamjoel
> > 
> > 
> > 我今天拉了代码，运行还是报这个错误。请问下env的三个参数，NEXT_PUBLIC_APP_ID填的是dify里对应的什么参数？
> 
> You can find the app id in the url of app detail page. <img alt="image" width="611" src="https://private-user-images.githubusercontent.com/2120155/367481302-67a0e54e-4df9-432b-8785-69856f219c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyODIzODQsIm5iZiI6MTcyNjI4MjA4NCwicGF0aCI6Ii8yMTIwMTU1LzM2NzQ4MTMwMi02N2EwZTU0ZS00ZGY5LTQzMmItODc4NS02OTg1NmYyMTljOTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMDI0ODA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2U2NGVlNWI3NTcyNzBiMzlmOTkxZGQzMTcwMjNiZWExODU5ODZmZmJiOGUzODdiMTEyMDNkZDI3MWJjNjE0OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2auz6qSVyeLCODshDPXC5MGzYkMP6ByRg81Pjg25A40">

Thank you. And it's my fault that I wrote wrong key and url which caused 500 err code. Now it works.

**Comment by scwu1008** [comment]
> 检查本地是否开了代理，把代理完全关闭去掉。

请问大佬知道这个是为什么吗？

**Comment by iamjoel** [comment]
> > 检查本地是否开了代理，把代理完全关闭去掉。
> 
> 请问大佬知道这个是为什么吗？

You can debug in  `app/api/parameters/route.ts` to find what's caused the problem.

**Comment by iamjoel** [comment]
> 怎么解决这个问题啊，我也500 App is unavailable

You can debug in app/api/parameters/route.ts to find what's caused the problem.

**Comment by BeiMeng** [comment]
npm run dev   请求  http://localhost:3000/api/conversations?limit=100&first_id=   返回  {"data":[],"error":"Invalid URL"}   怎么解决这个问题

**Comment by shenjilina** [comment]
http://localhost:3000/api/conversations?limit=100&first_id=
This api requests an error:  "Request failed with status code 400" 
Where is the documentation for this api?
