### ISSUE TITLE
 Something wrong with locale?

### ISSUE THREAD

**Issue by sean233** [langgenius/webapp-conversation#7]
<img width="883" alt="image" src="https://github.com/langgenius/webapp-conversation/assets/68827925/50894e0b-7e1e-41da-bcdc-ce529086af72">

**Comment by iamjoel** [comment]
I'll check it.

**Comment by 541013515** [comment]
how to fix it ？

**Comment by gadsdencode** [comment]
Any updates on how to fix this? I'm getting the same error.

**Comment by iamjoel** [comment]
Cannot reproduce. Try pulling the latest code to try it out.
