### ISSUE TITLE
开场问题没展示出来啊，看了看代码也没找到

### ISSUE THREAD

**Issue by tongwensen** [langgenius/webapp-conversation#72]
![1716273596140](https://github.com/langgenius/webapp-conversation/assets/31502700/fb35c489-fb30-4700-8aa0-e8231a69986e)

**Comment by tongwensen** [comment]
左侧是本地启动 右侧是云服务编排页面

**Comment by cuihj** [comment]
text_to_speech 语音转文字好像也没有处理

**Comment by Chinawv** [comment]
有后续的解决方案吗

**Comment by Jerryqjr** [comment]
如何增加这些功能呢

**Comment by marsDes** [comment]
@tongwensen @cuihj @Chinawv 
https://github.com/marsDes/webapp-conversation.git
新家开场问题。
后续会加入 推荐问题。 跟语音。
