### ISSUE TITLE
generationConversationName接口怎么使用？

### ISSUE THREAD

**Issue by fycfyc123** [langgenius/webapp-conversation#86]
export const generationConversationName = async (id: string) => {
  return post(`conversations/${id}/name`, { body: { auto_generate: true } })
}

这个是这个接口原本的样子，现在我想根据传递的name属性，去更改会话列表， 我在参数和body里面加了name，但是不好使啊，求助大佬 这是怎么回事啊

**Comment by iamjoel** [comment]
The api don't support change conversation name by the specified name.

**Comment by lanizz** [comment]
去掉auto_generate字段
```
export const generationConversationName = async (id: string, name:string) => {
    return post(conversations/${id}/name,  { body: { name } })
}
```

**Comment by wenmin92** [comment]
这个接口没有自动生成名称，调用时，即使加上 auto_generate 和 user 也不行，返回的都是 New conversation，只能通过 name 来强行命名成指定名称？
